# 네이버 주가 데이터 크롤링(일별시세)



Iframe 의 경우 일반적인 크롤링 방식으로는 콘텐츠를 가져오지 못함

src의 주소를 타고 들어가서 iframe에 해당하는 페이지로 직접 들어갸아함

In [2]:
import requests
from bs4 import BeautifulSoup as bs

In [102]:
import pandas as pd

In [74]:
base_url="https://finance.naver.com//item/sise_day.nhn"   #해당 iframe의 url
params={
    "code":'005930'
}
resp_stock=requests.get(base_url,params)

soup_stock=bs(resp_stock.text)
day_price=soup_stock.select("body > table.type2 tr")

In [76]:
tr_tags=soup_stock.select("table.type2 tr")
len(tr_tags)

16

In [85]:
result_stock=[]

th_tags=tr_tags[0].find_all("th")
title_list=[]
for th in th_tags:
    title_list.append(th.text)

for tr_tag in tr_tags:
    td_tags=tr_tag.find_all('td')
    if len(td_tags)<7:
        continue
    data_list=[]
    for td in td_tags:
        data_list.append(td.text.strip())
    result_stock.append(dict(zip(title_list,data_list)))

In [87]:
result_stock

[{'날짜': '2020.07.31',
  '종가': '58,900',
  '전일비': '100',
  '시가': '59,500',
  '고가': '59,600',
  '저가': '58,400',
  '거래량': '6,925,599'},
 {'날짜': '2020.07.30',
  '종가': '59,000',
  '전일비': '0',
  '시가': '59,700',
  '고가': '60,100',
  '저가': '59,000',
  '거래량': '19,285,354'},
 {'날짜': '2020.07.29',
  '종가': '59,000',
  '전일비': '400',
  '시가': '60,300',
  '고가': '60,400',
  '저가': '58,600',
  '거래량': '36,476,611'},
 {'날짜': '2020.07.28',
  '종가': '58,600',
  '전일비': '3,000',
  '시가': '57,000',
  '고가': '58,800',
  '저가': '56,400',
  '거래량': '48,431,566'},
 {'날짜': '2020.07.27',
  '종가': '55,600',
  '전일비': '1,400',
  '시가': '54,300',
  '고가': '55,700',
  '저가': '54,300',
  '거래량': '21,054,421'},
 {'날짜': '2020.07.24',
  '종가': '54,200',
  '전일비': '100',
  '시가': '54,000',
  '고가': '54,400',
  '저가': '53,700',
  '거래량': '10,994,535'},
 {'날짜': '2020.07.23',
  '종가': '54,100',
  '전일비': '600',
  '시가': '54,700',
  '고가': '54,700',
  '저가': '53,800',
  '거래량': '16,214,932'},
 {'날짜': '2020.07.22',
  '종가': '54,700',
  '전일비': '600',
  '시가': '55,300',
  '고가': '55,500',
  '저가': '54,700',
  '거래량': '12,885,057'},
 {'날짜': '2020.07.21',
  '종가': '55,300',
  '전일비': '1,100',
  '시가': '55,200',
  '고가': '55,400',
  '저가': '54,800',
  '거래량': '18,297,260'},
 {'날짜': '2020.07.20',
  '종가': '54,200',
  '전일비': '200',
  '시가': '54,800',
  '고가': '54,800',
  '저가': '54,000',
  '거래량': '10,507,530'}]

## 주가 크롤링 함수화

In [117]:
def get_day_price(code,page_num):
    
    result_stock=[]
    for page in range(1,page_num+1):  #검색하고자 하는 페이지 수 만큼 반복
        base_url="https://finance.naver.com//item/sise_day.nhn"   #해당 iframe의 url
        params={
            "code":code,
            "page":page}   #url에 들어갈 파라미터 설정 , 'code' : 종목코드 , "page" : 페이지 번호
        
        
        
        resp_stock=requests.get(base_url,params)   #해당 url에 리퀘스트
        soup_stock=bs(resp_stock.text) #Beautifulsoup 으로 받아온 url parsing 
        
        tr_tags=soup_stock.select("table.type2 tr") #크롤링 하고자 하는 태그에 접근
        

        th_tags=tr_tags[0].find_all("th")  #헤더만 검색, 딕셔너리의 key가 될 요소들
        title_list=[]
        for th in th_tags:
            title_list.append(th.text)

        for tr_tag in tr_tags:   #tr 태그를 돌면서
            td_tags=tr_tag.find_all('td') # 각 tr태그 내에 있는 td 태그들 검색
            if len(td_tags)<7: #td 태그들의 길이가 7이하면 무시 
                continue
            data_list=[]
            for td in td_tags: #td 태그내 각 정보들에 접근
                data_list.append(td.text.strip()) #해당 태그의 텍스트만 (정보만)
            result_stock.append(dict(zip(title_list,data_list)))
            
    return result_stock

In [118]:
sise=get_day_price("005930",3)
sise

[{'날짜': '2020.07.31',
  '종가': '58,600',
  '전일비': '400',
  '시가': '59,500',
  '고가': '59,600',
  '저가': '58,400',
  '거래량': '10,043,927'},
 {'날짜': '2020.07.30',
  '종가': '59,000',
  '전일비': '0',
  '시가': '59,700',
  '고가': '60,100',
  '저가': '59,000',
  '거래량': '19,285,354'},
 {'날짜': '2020.07.29',
  '종가': '59,000',
  '전일비': '400',
  '시가': '60,300',
  '고가': '60,400',
  '저가': '58,600',
  '거래량': '36,476,611'},
 {'날짜': '2020.07.28',
  '종가': '58,600',
  '전일비': '3,000',
  '시가': '57,000',
  '고가': '58,800',
  '저가': '56,400',
  '거래량': '48,431,566'},
 {'날짜': '2020.07.27',
  '종가': '55,600',
  '전일비': '1,400',
  '시가': '54,300',
  '고가': '55,700',
  '저가': '54,300',
  '거래량': '21,054,421'},
 {'날짜': '2020.07.24',
  '종가': '54,200',
  '전일비': '100',
  '시가': '54,000',
  '고가': '54,400',
  '저가': '53,700',
  '거래량': '10,994,535'},
 {'날짜': '2020.07.23',
  '종가': '54,100',
  '전일비': '600',
  '시가': '54,700',
  '고가': '54,700',
  '저가': '53,800',
  '거래량': '16,214,932'},
 {'날짜': '2020.07.22',
  '종가': '54,700',
  '전일비': '600',
  '시가': '55,300',
  '고가': '55,500',
  '저가': '54,700',
  '거래량': '12,885,057'},
 {'날짜': '2020.07.21',
  '종가': '55,300',
  '전일비': '1,100',
  '시가': '55,200',
  '고가': '55,400',
  '저가': '54,800',
  '거래량': '18,297,260'},
 {'날짜': '2020.07.20',
  '종가': '54,200',
  '전일비': '200',
  '시가': '54,800',
  '고가': '54,800',
  '저가': '54,000',
  '거래량': '10,507,530'},
 {'날짜': '2020.07.17',
  '종가': '54,400',
  '전일비': '600',
  '시가': '54,200',
  '고가': '54,700',
  '저가': '54,100',
  '거래량': '10,096,174'},
 {'날짜': '2020.07.16',
  '종가': '53,800',
  '전일비': '900',
  '시가': '54,800',
  '고가': '54,800',
  '저가': '53,800',
  '거래량': '16,779,127'},
 {'날짜': '2020.07.15',
  '종가': '54,700',
  '전일비': '900',
  '시가': '54,400',
  '고가': '55,000',
  '저가': '54,300',
  '거래량': '24,051,450'},
 {'날짜': '2020.07.14',
  '종가': '53,800',
  '전일비': '400',
  '시가': '53,700',
  '고가': '53,800',
  '저가': '53,200',
  '거래량': '14,269,484'},
 {'날짜': '2020.07.13',
  '종가': '53,400',
  '전일비': '700',
  '시가': '53,300',
  '고가': '53,800',
  '저가': '53,100',
  '거래량': '12,240,188'},
 {'날짜': '2020.07.10',
  '종가': '52,700',
  '전일비': '100',
  '시가': '53,100',
  '고가': '53,200',
  '저가': '52,300',
  '거래량': '13,714,746'},
 {'날짜': '2020.07.09',
  '종가': '52,800',
  '전일비': '200',
  '시가': '53,200',
  '고가': '53,600',
  '저가': '52,800',
  '거래량': '17,054,850'},
 {'날짜': '2020.07.08',
  '종가': '53,000',
  '전일비': '400',
  '시가': '53,600',
  '고가': '53,900',
  '저가': '52,900',
  '거래량': '19,664,652'},
 {'날짜': '2020.07.07',
  '종가': '53,400',
  '전일비': '1,600',
  '시가': '55,800',
  '고가': '55,900',
  '저가': '53,400',
  '거래량': '30,760,032'},
 {'날짜': '2020.07.06',
  '종가': '55,000',
  '전일비': '1,400',
  '시가': '54,000',
  '고가': '55,000',
  '저가': '53,800',
  '거래량': '19,856,623'},
 {'날짜': '2020.07.03',
  '종가': '53,600',
  '전일비': '700',
  '시가': '53,000',
  '고가': '53,600',
  '저가': '52,700',
  '거래량': '11,887,868'},
 {'날짜': '2020.07.02',
  '종가': '52,900',
  '전일비': '300',
  '시가': '52,100',
  '고가': '52,900',
  '저가': '52,100',
  '거래량': '14,142,583'},
 {'날짜': '2020.07.01',
  '종가': '52,600',
  '전일비': '200',
  '시가': '53,400',
  '고가': '53,600',
  '저가': '52,400',
  '거래량': '16,706,143'},
 {'날짜': '2020.06.30',
  '종가': '52,800',
  '전일비': '400',
  '시가': '53,900',
  '고가': '53,900',
  '저가': '52,800',
  '거래량': '21,157,172'},
 {'날짜': '2020.06.29',
  '종가': '52,400',
  '전일비': '900',
  '시가': '52,500',
  '고가': '53,200',
  '저가': '52,000',
  '거래량': '17,776,925'},
 {'날짜': '2020.06.26',
  '종가': '53,300',
  '전일비': '1,400',
  '시가': '52,800',
  '고가': '53,900',
  '저가': '52,200',
  '거래량': '21,575,360'},
 {'날짜': '2020.06.25',
  '종가': '51,900',
  '전일비': '1,000',
  '시가': '52,100',
  '고가': '53,000',
  '저가': '51,900',
  '거래량': '18,541,624'},
 {'날짜': '2020.06.24',
  '종가': '52,900',
  '전일비': '1,500',
  '시가': '51,900',
  '고가': '53,900',
  '저가': '51,600',
  '거래량': '24,519,552'},
 {'날짜': '2020.06.23',
  '종가': '51,400',
  '전일비': '600',
  '시가': '52,500',
  '고가': '52,800',
  '저가': '51,100',
  '거래량': '18,086,152'},
 {'날짜': '2020.06.22',
  '종가': '52,000',
  '전일비': '900',
  '시가': '52,000',
  '고가': '52,600',
  '저가': '51,800',
  '거래량': '13,801,350'}]

## Pandas Excel(csv) IO

In [119]:
sise_df=pd.DataFrame(sise)
sise_df

            날짜      종가    전일비      시가      고가      저가         거래량
0   2020.07.31  58,600    400  59,500  59,600  58,400  10,043,927
1   2020.07.30  59,000      0  59,700  60,100  59,000  19,285,354
2   2020.07.29  59,000    400  60,300  60,400  58,600  36,476,611
3   2020.07.28  58,600  3,000  57,000  58,800  56,400  48,431,566
4   2020.07.27  55,600  1,400  54,300  55,700  54,300  21,054,421
5   2020.07.24  54,200    100  54,000  54,400  53,700  10,994,535
6   2020.07.23  54,100    600  54,700  54,700  53,800  16,214,932
7   2020.07.22  54,700    600  55,300  55,500  54,700  12,885,057
8   2020.07.21  55,300  1,100  55,200  55,400  54,800  18,297,260
9   2020.07.20  54,200    200  54,800  54,800  54,000  10,507,530
10  2020.07.17  54,400    600  54,200  54,700  54,100  10,096,174
11  2020.07.16  53,800    900  54,800  54,800  53,800  16,779,127
12  2020.07.15  54,700    900  54,400  55,000  54,300  24,051,450
13  2020.07.14  53,800    400  53,700  53,800  53,200  14,269,484
14  2020.07.13  53,400    700  53,300  53,800  53,100  12,240,188
15  2020.07.10  52,700    100  53,100  53,200  52,300  13,714,746
16  2020.07.09  52,800    200  53,200  53,600  52,800  17,054,850
17  2020.07.08  53,000    400  53,600  53,900  52,900  19,664,652
18  2020.07.07  53,400  1,600  55,800  55,900  53,400  30,760,032
19  2020.07.06  55,000  1,400  54,000  55,000  53,800  19,856,623
20  2020.07.03  53,600    700  53,000  53,600  52,700  11,887,868
21  2020.07.02  52,900    300  52,100  52,900  52,100  14,142,583
22  2020.07.01  52,600    200  53,400  53,600  52,400  16,706,143
23  2020.06.30  52,800    400  53,900  53,900  52,800  21,157,172
24  2020.06.29  52,400    900  52,500  53,200  52,000  17,776,925
25  2020.06.26  53,300  1,400  52,800  53,900  52,200  21,575,360
26  2020.06.25  51,900  1,000  52,100  53,000  51,900  18,541,624
27  2020.06.24  52,900  1,500  51,900  53,900  51,600  24,519,552
28  2020.06.23  51,400    600  52,500  52,800  51,100  18,086,152
29  2020.06.22  52,000    900  52,000  52,600  51,800  13,801,350

In [121]:
sise_df.to_csv("my_sise.csv",encoding='cp949')

In [122]:
#인덱스를 받아옴

temp=pd.read_csv("my_sise.csv",encoding='cp949')
temp

    Unnamed: 0          날짜      종가    전일비      시가      고가      저가         거래량
0            0  2020.07.31  58,600    400  59,500  59,600  58,400  10,043,927
1            1  2020.07.30  59,000      0  59,700  60,100  59,000  19,285,354
2            2  2020.07.29  59,000    400  60,300  60,400  58,600  36,476,611
3            3  2020.07.28  58,600  3,000  57,000  58,800  56,400  48,431,566
4            4  2020.07.27  55,600  1,400  54,300  55,700  54,300  21,054,421
5            5  2020.07.24  54,200    100  54,000  54,400  53,700  10,994,535
6            6  2020.07.23  54,100    600  54,700  54,700  53,800  16,214,932
7            7  2020.07.22  54,700    600  55,300  55,500  54,700  12,885,057
8            8  2020.07.21  55,300  1,100  55,200  55,400  54,800  18,297,260
9            9  2020.07.20  54,200    200  54,800  54,800  54,000  10,507,530
10          10  2020.07.17  54,400    600  54,200  54,700  54,100  10,096,174
11          11  2020.07.16  53,800    900  54,800  54,800  53,800  16,779,127
12          12  2020.07.15  54,700    900  54,400  55,000  54,300  24,051,450
13          13  2020.07.14  53,800    400  53,700  53,800  53,200  14,269,484
14          14  2020.07.13  53,400    700  53,300  53,800  53,100  12,240,188
15          15  2020.07.10  52,700    100  53,100  53,200  52,300  13,714,746
16          16  2020.07.09  52,800    200  53,200  53,600  52,800  17,054,850
17          17  2020.07.08  53,000    400  53,600  53,900  52,900  19,664,652
18          18  2020.07.07  53,400  1,600  55,800  55,900  53,400  30,760,032
19          19  2020.07.06  55,000  1,400  54,000  55,000  53,800  19,856,623
20          20  2020.07.03  53,600    700  53,000  53,600  52,700  11,887,868
21          21  2020.07.02  52,900    300  52,100  52,900  52,100  14,142,583
22          22  2020.07.01  52,600    200  53,400  53,600  52,400  16,706,143
23          23  2020.06.30  52,800    400  53,900  53,900  52,800  21,157,172
24          24  2020.06.29  52,400    900  52,500  53,200  52,000  17,776,925
25          25  2020.06.26  53,300  1,400  52,800  53,900  52,200  21,575,360
26          26  2020.06.25  51,900  1,000  52,100  53,000  51,900  18,541,624
27          27  2020.06.24  52,900  1,500  51,900  53,900  51,600  24,519,552
28          28  2020.06.23  51,400    600  52,500  52,800  51,100  18,086,152
29          29  2020.06.22  52,000    900  52,000  52,600  51,800  13,801,350

In [123]:
#index_col을 통해 인덱스 제거
temp=pd.read_csv("my_sise.csv",encoding='cp949',index_col=0)
temp

            날짜      종가    전일비      시가      고가      저가         거래량
0   2020.07.31  58,600    400  59,500  59,600  58,400  10,043,927
1   2020.07.30  59,000      0  59,700  60,100  59,000  19,285,354
2   2020.07.29  59,000    400  60,300  60,400  58,600  36,476,611
3   2020.07.28  58,600  3,000  57,000  58,800  56,400  48,431,566
4   2020.07.27  55,600  1,400  54,300  55,700  54,300  21,054,421
5   2020.07.24  54,200    100  54,000  54,400  53,700  10,994,535
6   2020.07.23  54,100    600  54,700  54,700  53,800  16,214,932
7   2020.07.22  54,700    600  55,300  55,500  54,700  12,885,057
8   2020.07.21  55,300  1,100  55,200  55,400  54,800  18,297,260
9   2020.07.20  54,200    200  54,800  54,800  54,000  10,507,530
10  2020.07.17  54,400    600  54,200  54,700  54,100  10,096,174
11  2020.07.16  53,800    900  54,800  54,800  53,800  16,779,127
12  2020.07.15  54,700    900  54,400  55,000  54,300  24,051,450
13  2020.07.14  53,800    400  53,700  53,800  53,200  14,269,484
14  2020.07.13  53,400    700  53,300  53,800  53,100  12,240,188
15  2020.07.10  52,700    100  53,100  53,200  52,300  13,714,746
16  2020.07.09  52,800    200  53,200  53,600  52,800  17,054,850
17  2020.07.08  53,000    400  53,600  53,900  52,900  19,664,652
18  2020.07.07  53,400  1,600  55,800  55,900  53,400  30,760,032
19  2020.07.06  55,000  1,400  54,000  55,000  53,800  19,856,623
20  2020.07.03  53,600    700  53,000  53,600  52,700  11,887,868
21  2020.07.02  52,900    300  52,100  52,900  52,100  14,142,583
22  2020.07.01  52,600    200  53,400  53,600  52,400  16,706,143
23  2020.06.30  52,800    400  53,900  53,900  52,800  21,157,172
24  2020.06.29  52,400    900  52,500  53,200  52,000  17,776,925
25  2020.06.26  53,300  1,400  52,800  53,900  52,200  21,575,360
26  2020.06.25  51,900  1,000  52,100  53,000  51,900  18,541,624
27  2020.06.24  52,900  1,500  51,900  53,900  51,600  24,519,552
28  2020.06.23  51,400    600  52,500  52,800  51,100  18,086,152
29  2020.06.22  52,000    900  52,000  52,600  51,800  13,801,350

In [130]:
import openpyxl  #엑셀파일 읽기 위해
import xlrd

In [131]:
sise_df.to_excel("my_second_sise.xlsx",encoding="cp949")

In [132]:
temp_xl=pd.read_excel("my_second_sise.xlsx",encoding="cp949",index_col=0)

In [142]:
temp_xl

            날짜      종가    전일비      시가      고가      저가         거래량
0   2020.07.31  58,600    400  59,500  59,600  58,400  10,043,927
1   2020.07.30  59,000      0  59,700  60,100  59,000  19,285,354
2   2020.07.29  59,000    400  60,300  60,400  58,600  36,476,611
3   2020.07.28  58,600  3,000  57,000  58,800  56,400  48,431,566
4   2020.07.27  55,600  1,400  54,300  55,700  54,300  21,054,421
5   2020.07.24  54,200    100  54,000  54,400  53,700  10,994,535
6   2020.07.23  54,100    600  54,700  54,700  53,800  16,214,932
7   2020.07.22  54,700    600  55,300  55,500  54,700  12,885,057
8   2020.07.21  55,300  1,100  55,200  55,400  54,800  18,297,260
9   2020.07.20  54,200    200  54,800  54,800  54,000  10,507,530
10  2020.07.17  54,400    600  54,200  54,700  54,100  10,096,174
11  2020.07.16  53,800    900  54,800  54,800  53,800  16,779,127
12  2020.07.15  54,700    900  54,400  55,000  54,300  24,051,450
13  2020.07.14  53,800    400  53,700  53,800  53,200  14,269,484
14  2020.07.13  53,400    700  53,300  53,800  53,100  12,240,188
15  2020.07.10  52,700    100  53,100  53,200  52,300  13,714,746
16  2020.07.09  52,800    200  53,200  53,600  52,800  17,054,850
17  2020.07.08  53,000    400  53,600  53,900  52,900  19,664,652
18  2020.07.07  53,400  1,600  55,800  55,900  53,400  30,760,032
19  2020.07.06  55,000  1,400  54,000  55,000  53,800  19,856,623
20  2020.07.03  53,600    700  53,000  53,600  52,700  11,887,868
21  2020.07.02  52,900    300  52,100  52,900  52,100  14,142,583
22  2020.07.01  52,600    200  53,400  53,600  52,400  16,706,143
23  2020.06.30  52,800    400  53,900  53,900  52,800  21,157,172
24  2020.06.29  52,400    900  52,500  53,200  52,000  17,776,925
25  2020.06.26  53,300  1,400  52,800  53,900  52,200  21,575,360
26  2020.06.25  51,900  1,000  52,100  53,000  51,900  18,541,624
27  2020.06.24  52,900  1,500  51,900  53,900  51,600  24,519,552
28  2020.06.23  51,400    600  52,500  52,800  51,100  18,086,152
29  2020.06.22  52,000    900  52,000  52,600  51,800  13,801,350